### ISSUE TITLE
Php Files

### ISSUE THREAD

**Issue by ghost** [simlar/simlar-android#212]
First of all, Congratulations on the good work you all doing. Second, could i please have the create-account.php file ? Please :)  found in CreateAccount.java ?

**Comment by BenSartor** [comment]
Hi Hamid,

good think, you moved our discussion to github.

Let me repeat this for the public: Opensourcing the server side scripts is on my schedule. But like always I do not want to make any promises when it will happen. At the moment these scripts e.g. contain some passwords and vendor specific implementation which need to to be splitted out.

As you can imagine create-account.php is highly dependent on our sms-gateways. But maybe a code snippet helps you again.

```php
function requestAccountCreation($telephoneNumber, $smsText, $ip)
{
	// do some checks

	$password = generatePassword(12);
	$registrationCode = mt_rand(100000, 999999);

	sendSms($db, $telephoneNumber, createSmsText($smsText, $registrationCode));

	// save request

	xmlResponse("success", array ("simlarId" => $simlarId, "password" => $password));
}

function confirmAccountCreation($simlarId, $registrationCode)
{
	// check simlarId
	// check registration code
	// add simlarID and password to you sip servers db
	xmlResponse("success", array ("simlarId" => $simlarId, "registrationCode" => $registrationCode));
}
```

**Comment by SudoAccess** [comment]
Hey Ben,
I think i posted this issue before i checked my email or something. anyway  i really like the Job you are doing. I am your biggest simlar fan :) :+1:  . I will integrate the code with my own sms gateway. 

But then again, SMS-Gateways are expensive on a larger scale, have you ever thought of how accounts can be verified without Sms ?

Thanks A lot Ben. I Support Simlar :+1:

**Comment by BenSartor** [comment]
Hi Hamid,

yes, we have thought about receiving SMSes on the server to verify the clients telephone number. But the offers I found for that, all have a monthly fee which at moment is not much less than the amount we pay for SMS. So we decided to not let the simlar users pay for a sms to e.g. germany and bear the costs ourselfs. However we might reconsider this decision once our daily registrations increase.

Cheers,
 Ben

**Comment by SudoAccess** [comment]
i have setup my sip server and turn server too. i have an sms contract to send verification sms too. but i am unable to use simlar because i still cant get the php files :( @BenSartor . my sip server works with all sip clients , is there any hack i can use to test simlar ? or is there any solution if i cant get the php files ? :(

**Comment by BenSartor** [comment]
I am working on a rewrite of the scripts in java in order to publish it.
