### ISSUE TITLE
Sample User Case

### ISSUE THREAD

**Issue by SudoAccess** [simlar/simlar-android#224]
here is my user case. my users are registered and verified with my own server and at the same time the users are registered with kamailio. Is it possible for me to remove simlars sms verification and when a user clicks on the call button, a sip call will be started with the contact ? 
e.g test@209.89.0.1.2 

is this possible with simlar ? if not what do you suggest ?

**Comment by DennisKlipp** [comment]
Hi SudoAccess,

i didn't understand what you wanna do exactly. But I guess you wanna built your own Simlar-Server.

Im sorry to tell you, that we actually do not support this feature.

Regards
Dennis
