### ISSUE TITLE
Not receiving SMS Verification

### ISSUE THREAD

**Issue by ianseyer** [simlar/simlar-android#239]
Attempted multiple times

Nexus 5X, Android 6.0
clean install.
Located in Austin, TX, USA

**Comment by BenSartor** [comment]
Hi,

sorry for the late reply. Occasionally our SMS-Provider has Problems sending SMS to specific numbers. Would you mind trying again? If it still does not work, would you mind sending an email at support@simlar.org? It is important to include your telephone number in that email, so we can check with our SMS-Provider.

Cheers,
 Ben
