### ISSUE TITLE
Cannot read SMS verification code/connection problems with software VPN/"Firewal without root" app

### ISSUE THREAD

**Issue by rugk** [simlar/simlar-android#245]
I use Signal to receive SMS. And as Signal does not seem to allow other apps to access SMS the verification in the app always fails with an error "The server could not be reached. Please try again later:"

This is not only a confusing error message (as the server could be reached and I saw that the I received the message) - there is also no possibility to skip this error message and enter the code manually.

Simlar v1.6.0 (installed from Google Play)
Android 5.0.1

**Comment by rugk** [comment]
Okay I also seem to get this error when I use the default SMS app so it is possibly really an error when connecting to the server as it seems to display "finishing registration" (or similar) for some seconds.

**Comment by BenSartor** [comment]
Hi @rugk,
I have just checked that the Simlar registration works when Signal is installed. There also is a widget to type in the registration code manually. You just have to wait till the timeout ends.

Where exactly does your registration hang? "Confirm account creation" or "First login"?

**Comment by rugk** [comment]
[**@BenSartor**](https://github.com/BenSartor) commented on [7. Jan. 2016, 00:08 MEZ](https://github.com/simlar/simlar-android/issues/245#issuecomment-169491051 "2016-01-06T23:08:41Z - Replied by Github Comment Enhancer"):
> Hi [@rugk](https://github.com/rugk),  
> Where exactly does your registration hang? "Confirm account creation" or "First login"?

I assume it is "First login".

**Comment by BenSartor** [comment]
Hi @rugk,
in this step the sms has been read successfully. But you have problems to connect to the sip server.

What happens if you start Simlar again? Do see the address book?

**Comment by rugk** [comment]
Finally I've found the culprit: https://play.google.com/store/apps/details?id=app.greyshirts.firewall

Of course I allowed complete access for the app and as you can see the SMS also could be send successfully, but it could not contact the server afterwards.
By temporarily disabling the firewall I could resolve the issue and go on.

It would be nice if you could have a look whether you can fix this.

**Comment by jritzerfeld** [comment]
AFAIK NoRoot Firewall does not really support VoIP/SIP apps. NoRoot Firewall Beta has "Better VoIP support". However, both apps have not been updated since 2014. I am afraid there is nothing we can do about that.
