### ISSUE TITLE
App doesn't load on iOS after verifying text and accepting contact the app crashes

### ISSUE THREAD

**Issue by dk212** [simlar/simlar-android#274]
multiple tries of installing and uninstalling
the wheel spins for a few seconds and then crashes and closes
yet others see the user as registered in their contact list
but it never loads

**Comment by BenSartor** [comment]
Hello @dk212,
would you be so kind and send us a log file of the crash?
You can do this e.g. as follows:

- Open the iOS settings app and go to Simlar.
- Turn on logging.
- Reproduce the crash.
- Goto the Simlar Settings again.
- Turn on "Report Bug next start".
- Start Simlar again.

Regards,
 Ben

**Comment by jritzerfeld** [comment]
@dk212 This should be fixed by https://github.com/simlar/simlar-ios/pull/70
