### ISSUE TITLE
Whatsup & Simlar

### ISSUE THREAD

**Issue by MyraBaba** [simlar/simlar-android#277]
Hi Ben,

We are testing simlar for a while . We wonder what is the differences between whatsup call and the simlar call both connection & voice quality ?

Basicly we have trouble to connect simlar in some networks. Some time can not . Is waiting to encrytion & quality screen beeping and not connecting.  than we try whatsup , its connection without any problem. same time same network same phone. (generally in mobile high speed networks)

How we can improve this connection quality ? Do you have an idea or suspected problem why we have such problem.

thx

**Comment by jritzerfeld** [comment]
Hey MyraBaba,

in which state exactly is Simlar stuck? The messages Simlar displays are the following (in that order): 
1. Connecting to server
2. Waiting for contact
3. Ringing
4. Encrypting
5. Talking

Kind regards,
 Jan

**Comment by MyraBaba** [comment]
Hi,

The most annoying is the Encryption stuck.  It says different quality connection and trying to encryption or connect.  It is happening after both side answer the phone. There is endless delay .  Same situation whatsup connect and start to talking immediately.

What we can do ?


thx

**Comment by jritzerfeld** [comment]
Sorry, I’m afraid I don’t follow you. What do you mean by "it says different quality connection"? While Simlar is trying to connect to server or encrypting, where do you see the quality of the connection?

However, if you immediately try to make a call the other person again, does it work then?

**Comment by MyraBaba** [comment]
It means there is https://camo.githubusercontent.com/3d2e6b4832ced995b987cf02c9178f9d7b7ca992/68747470733a2f2f7777772e73696d6c61722e6f72672f70726573732f73637265656e73686f74732f416e64726f69642f656e2f74616c6b696e672d746f2d736f2e706e67 <https://camo.githubusercontent.com/3d2e6b4832ced995b987cf02c9178f9d7b7ca992/68747470733a2f2f7777772e73696d6c61722e6f72672f70726573732f73637265656e73686f74732f416e64726f69642f656e2f74616c6b696e672d746f2d736f2e706e67>   

network quality 


It is changing when try to connect. 

It is stucking trying to encryption…  


but we can connect whatsup without no problem.

**Comment by BenSartor** [comment]
Hello @MyraBaba,
as Simlar uses ZRTP there is an encryption handshake on the beginning of each call. However when having packet loss, this handshake may take longer or fail.

Most of the time it helps to try calling again.
Did you try that?

I do not know WhatsApp well enough, but maybe their encryption works differently.

Regards,
 Ben

**Comment by jritzerfeld** [comment]
No response.
