### ISSUE TITLE
No connection to server

### ISSUE THREAD

**Issue by hum-man** [simlar/simlar-android#306]
Hi Ben,
with simlar allways online i have trouble connecting the server from south america. This happens with versions 1.6.0, 1.8.2, 1.9.1, other versions I did not test so far. With version 1.6.0 i could get  server connection after 3-6 trials, the other testet versions fail completly. 

In Germany I had no problem with Version 1.6.0 but did not test the others.

Google-play version 1.9.1 on friends smartphones work fine.

Hardware: LG L5, Carbon-ROM Caliblack 4.2-4.4.4, Skernel 3.4.108

**Comment by BenSartor** [comment]
Hello @hum-man,

sorry for replying so late.
We had some server issues around the 2017-06-09. Maybe you hit them.

If the problem still appears, would you try to upload a logfile?
I have just created a little wiki page describing how to do this:
[Upload a log file with Simlar Android](https://github.com/simlar/simlar-android/wiki/Upload-a-log-file-with-Simlar-Android)

Regards,
 Ben

**Comment by jritzerfeld** [comment]
No response.
