### ISSUE TITLE
custom server address

### ISSUE THREAD

**Issue by jasmith1338** [simlar/simlar-android#389]
If I build this from scratch using the Similar-server
where would I put the server ip/info to commute back to the custom server within the android client source code?

**Comment by BenSartor** [comment]
You may do this in `app/src/main/java/org/simlar/helper/ServerSettings.java`.
Furthermore you should at least update the `applicationId` in `app/build.gradle` and the `app_name` in `app/src/main/res/values/strings.xml`.
If you want to use push notification updating `app/google-services.json` is also required.

Documenting how to run your own server is still on my todo list. But I do not think I will find time for it anytime soon. However help is always welcome :)
