### ISSUE TITLE
APK Download / F-Droid Repo Down

### ISSUE THREAD

**Issue by ghost** [simlar/simlar-android#394]
Hi

I visited you at FroSCon.
You said there is a APK Download on your website, but I didn't found anything.
Can you help me to find a GApps free apk?

Do you know that your F-Droid Repo is down?

Thanks.

**Comment by BenSartor** [comment]
Hi,

we are working on the frdroid repo.

Meanwhile you may download the apk here:
https://www.simlar.org/devel/android/

Cheers,
 Ben

**Comment by beli3ver** [comment]
Maybe you can make a simple button on your site, so everybody can found it.

Malte

Am 10. August 2019 17:58:14 MESZ schrieb Ben Sartor <notifications@github.com>:
>Hi,
>
>we are working on the frdroid repo.
>
>Meanwhile you may download the apk here:
>https://www.simlar.org/devel/android/
>
>Cheers,
> Ben
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/simlar/simlar-android/issues/394#issuecomment-520159756

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by BenSartor** [comment]
Hi @beli3ver,
thanks again for all your contributions!
@DennisKlipp updated our homepage yesterday.
Cheers,
 Ben
