### ISSUE TITLE
[F-Droid] Process to integrate simlar to fdroid main repo

### ISSUE THREAD

**Issue by ghost** [simlar/simlar-android#396]
HI.

I created a request to include simlar to the fdroid main repo: https://gitlab.com/fdroid/rfp/issues/1063

To do this, first you must change the gradle script. Answer from one of the fdroid maintainer:

> We won't be able to automatically detect updates, though – due to non-static versionName/versionCode in build.gradle (our update checker currently only parses the build.gradle using RegEx, it doesn't run gradlew.

So is it possible, that you change this?

**Comment by beli3ver** [comment]
Also there must be a distributionSha256Sum in the gradle/wrapper/gradle.properties file. Like this:

```
#Sun Apr 21 10:59:16 CEST 2019
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip
distributionSha256Sum=53b71812f18cdb2777e9f1b2a0f2038683907c90bdc406bc64d8b400e1fb2c3b
```

**Comment by beli3ver** [comment]
And for the maven part we must do this:

> But, you can just use the Linphone metadata and copy the build part where the AAR is compiled, then copy that to your app folder before actually building Simlar

**Comment by BenSartor** [comment]
Hi @beli3ver,
I think we have just fixed the distributionSha256Sum problem.
I will have a look at the versionName/versionCode, too.
