### ISSUE TITLE
simlar is down

### ISSUE THREAD

**Issue by jollykin** [simlar/simlar-android#418]
always shows connecting to server,

i think server is down from last 2 days

**Comment by BenSartor** [comment]
Thanks a lot for reporting and sorry for the late reply.
Meanwhile the server is up again.

**Comment by jollykin** [comment]
hi dear,

again always shows connecting to server,

i think server is down from last 2 days


regards
jolly


Dec 23, 2019, 22:06 by notifications@github.com:

**Comment by jollykin** [comment]
???????????????

Jan 2, 2020, 12:20 by jollykin@tuta.io:
