### ISSUE TITLE
does not work with Christian's ISP

### ISSUE THREAD

**Issue by BenSartor** [simlar/simlar-android#6]
Simlar does not work at Christians home. It works using UMTS or at his moms house. Normal Internet works.

What I have tested so far:

old.server: no network packages comming in

new server:
- new ip, new server, new Rechenzentrum
- Creating an Account over port 6161 works
- Logging in via sip (tls port 5061) does not
- Switched sip port to 443 (still tls, still tcp) => does not work
- Although some packages come through
  *\* have to sniff agaian
- Tried decreasing mtu
  *\* I do not know if it works in the lxc setup we use. Here is what I did
  *\* Guest: /etc/network/interfaces: set mtu to 1100
  *\* Host: disabled clamp-mms (temporarily)
  *\* Host: set mtu in /etc/lxc/simlar.org.conf

Status:
- I left mtu and port settings at sip.simlar.org, as other locations work. Of course I turned on clamp-mms again.
- I might decide to switch back any time near.
- Christian is on holiday: 20.10. - 26.10.

Conclusion:
- I would like to test a root server.
- It is needed to visit Christian.

Christian WLAN router: dlink di-524
https://www.kabelbw.de/kabelbw/cms/downloads/kabel-bw-di-524-install.pdf [^]

**Comment by jritzerfeld** [comment]
Is this issue still reproducable?

**Comment by BenSartor** [comment]
No.
